---
booktitle: Proceedings of the Learning to Rank Challenge
logoright: ltrc_logo.jpg
month: 0
publisher: PMLR
volume: 14
year: '2010'
start: 2010-06-25
end: 2010-06-25
published: 2011-01-26
shortname: Learning to Rank Challenge
sections:
- name: preface
  title: Introduction
- name: default
  title: Contributed Papers
- name: afterword
  title: Afterword
layout: proceedings
series: Proceedings of Machine Learning Research
id: ChapelleLearning2010
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
cycles: false
editor:
- given: Olivier
  family: Chapelle
- given: Yi
  family: Chang
- given: Tie-Yan
  family: Liu
description: |
  Proceedings of the Learning to Rank Challenge
    Held in Haifa, Israel on 25 June 2010

  Published as Volume 14 by the Proceedings of Machine Learning Research on 26 January 2011.

  Volume Edited by:
    Olivier Chapelle
    Yi Chang
    Tie-Yan Liu

  Series Editors:
    Neil D. Lawrence
date_str: 25 Jun
url: http://proceedings.mlr.press
baseurl: "/v14"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v14
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Proceedings of the Learning to Rank Challenge
  url: 
  location: Haifa, Israel
  dates:
  - 2010-06-25
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v14.bib
