---
booktitle: Proceedings of the Learning to Rank Challenge
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
logo: ltrc_logo.jpg
month: 0
publisher: PMLR
volume: 14
year: '2010'
start: 2010-06-25
end: 2010-06-25
published: 2011-01-26
shortname: Learning to Rank Challenge
sections:
- name: preface
  title: Introduction
- name: default
  title: Contributed Papers
- name: afterword
  title: Afterword
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: ChapelleLearning2010
cycles: false
editor:
- given: Olivier
  family: Chapelle
- given: Yi
  family: Chang
- given: Tie-Yan
  family: Liu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Learning to Rank Challenge
    Held in Haifa, Israel on 25 June 2010

  Published as Volume 14 by the Proceedings of Machine Learning Research on 26 January 2011.

  Volume Edited by:
    Olivier Chapelle
    Yi Chang
    Tie-Yan Liu

  Series Editors:
    Neil D. Lawrence
date_str: 25 Jun
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v14"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v14
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Proceedings of the Learning to Rank Challenge
  url: 
  location: Haifa, Israel
  dates:
  - 2010-06-25
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
